### ISSUE TITLE
Possible bad link in notes pages at this link https://vickiboykis.com/ml-garden/

### ISSUE THREAD

**Issue by KomiB-Atsou** [veekaybee/ml-garden#2]
Hi Vicky,

Hope you are doing well.
Thank you for sharing on your blog.

At this link [Machine Learning Garden (vickiboykis.com)](https://vickiboykis.com/ml-garden/), I think the link of the doc framed in this snapshot is not the good one. Can you check please?

![image](https://github.com/user-attachments/assets/2a70dec0-027c-4b4d-ad5b-dece9ee81e9f)

The link about Algorithms and OOP in Java is the same as the link for Lecture on HNSW and Graph Search

**Comment by veekaybee** [comment]
Thanks for this! Fixed with https://github.com/veekaybee/ml-garden/commit/c8031005803ca79c55eaa1ad3d8a56856ae9f04f
